//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aws_speech.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aws_speech.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Values&quot;: [
        ///      1.0,
        ///      0.0
        ///    ],
        ///    &quot;Targets&quot;: [
        ///      1.0
        ///    ]
        ///  },
        ///  {
        ///    &quot;Values&quot;: [
        ///      0.0,
        ///      1.0
        ///    ],
        ///    &quot;Targets&quot;: [
        ///      1.0
        ///    ]
        ///  },
        ///  {
        ///    &quot;Values&quot;: [
        ///      0.0,
        ///      0.0
        ///    ],
        ///    &quot;Targets&quot;: [
        ///      0.0
        ///    ]
        ///  },
        ///  {
        ///    &quot;Values&quot;: [
        ///      1.0,
        ///      1.0
        ///    ],
        ///    &quot;Targets&quot;: [
        ///      0.0
        ///    ]
        ///  }
        ///].
        /// </summary>
        internal static string DatasetExample {
            get {
                return ResourceManager.GetString("DatasetExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;LearnRate&quot;: 0.4,
        ///  &quot;Momentum&quot;: 0.9,
        ///  &quot;InputLayer&quot;: [
        ///    {
        ///      &quot;Id&quot;: &quot;f1fea97c-48ba-4e1b-b7eb-fe9d1897758c&quot;,
        ///      &quot;Bias&quot;: 0.88011651853104889,
        ///      &quot;BiasDelta&quot;: 0.0,
        ///      &quot;Gradient&quot;: 0.0,
        ///      &quot;Value&quot;: 0.0
        ///    },
        ///    {
        ///      &quot;Id&quot;: &quot;fcf15808-fb11-4a04-9022-638140164c64&quot;,
        ///      &quot;Bias&quot;: -0.12904600665394495,
        ///      &quot;BiasDelta&quot;: 0.0,
        ///      &quot;Gradient&quot;: 0.0,
        ///      &quot;Value&quot;: 0.0
        ///    }
        ///  ],
        ///  &quot;HiddenLayers&quot;: [
        ///    [
        ///      {
        ///        &quot;Id&quot;: &quot;2cc0c76b-1c40-4c72-803f-97c0997bcc07&quot;,
        ///        &quot;Bias&quot;: 1.6459098726 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NetworkExample {
            get {
                return ResourceManager.GetString("NetworkExample", resourceCulture);
            }
        }
    }
}
